version: '3.9'

services:
  web-nginx:
    # Debian GNU/Linux 12 (bookworm)
    image: nginx:latest
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_PORT_TLS:-443}:443"
    volumes:
      - ./src:/var/www/dev.org/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/certs:/etc/nginx/certs
    links:
      - php-fpm
  php-fpm:
    build: ./config/php
    volumes:
      - ./src:/var/www/dev.org/html
      - ./config/php/conf.d:/usr/local/etc/php/conf.d
      - ./config/php/php.ini-development:/usr/local/etc/php/php.ini-development
      - ./config/php/php.ini-production:/usr/local/etc/php/php.ini-production